### ISSUE TITLE
Sub-selected columns

### ISSUE THREAD

**Issue by codenamev** [bogdan/datagrid#159]
Any ideas how I'd implement this Scenario?

```ruby
  column(:sub_select_column, "(SELECT name FROM countries WHERE id=10)")
```

**Comment by bogdan** [comment]
It should just work. Do you have any problem or exception message?

**Comment by codenamev** [comment]
It seems the columns don't actually use the scope as a reference, so I get undefined method `sub_select_column` in the views as it's not attaching the custom select/column to the base scope.

**Comment by bogdan** [comment]
Please give me the result of `grid.assets.to_sql`.

**Comment by codenamev** [comment]
it seems the query is there as I would get `SELECT accounts.*, (SELECT name FROM countries WHERE id=10) AS sub_select_column ...`, but then it hits the view helper for `datagrid/_row.html.erb` and I get:

```
NoMethodError - undefined method `sub_select_column' for #<Model:...>:
  datagrid (1.3.9) lib/datagrid/columns.rb:215:in `block in define_column'
  datagrid (1.3.9) lib/datagrid/utils.rb:72:in `apply_args'
  datagrid (1.3.9) lib/datagrid/columns.rb:474:in `block in generic_value'
  datagrid (1.3.9) lib/datagrid/columns.rb:488:in `cache'
  datagrid (1.3.9) lib/datagrid/columns.rb:468:in `generic_value'
  datagrid (1.3.9) lib/datagrid/columns.rb:460:in `block in html_value'
  datagrid (1.3.9) lib/datagrid/columns.rb:488:in `cache'
  datagrid (1.3.9) lib/datagrid/columns.rb:456:in `html_value'
  datagrid (1.3.9) lib/datagrid/renderer.rb:19:in `format_value'
  datagrid (1.3.9) lib/datagrid/helper.rb:17:in `datagrid_value'
  datagrid (1.3.9) app/views/datagrid/_row.html.erb:3
```

**Comment by bogdan** [comment]
`...` matter. Please show full query. I found an interesting AR behaviour:

```
2.2.2 :022 > User.preload(:account).select("users.*", "users.id+100 as shifted_id").first.shifted_id
  User Load (0.4ms)  SELECT  users.*, users.id+100 as shifted_id FROM `users`  ORDER BY `users`.`id` ASC LIMIT 1
  Account Load (0.2ms)  SELECT `accounts`.* FROM `accounts` WHERE `accounts`.`id` IN (126)
 => 101
2.2.2 :023 > User.eager_load(:account).select("users.*", "users.id+100 as shifted_id").first.shifted_id
  SQL (0.5ms)  SELECT  users.*, users.id+100 as shifted_id, `users`.`id` AS t0_r0, `users`.`email` AS t0_r1, `users`.`crypted_password` AS t0_r2, `users`.`password_salt` AS t0_r3, `users`.`persistence_token` AS t0_r4, `users`.`single_access_token` AS t0_r5, `users`.`perishable_token` AS t0_r6, `users`.`login_count` AS t0_r7, `users`.`failed_login_count` AS t0_r8, `users`.`last_request_at` AS t0_r9, `users`.`current_login_at` AS t0_r10, `users`.`last_login_at` AS t0_r11, `users`.`current_login_ip` AS t0_r12, `users`.`last_login_ip` AS t0_r13, `users`.`created_at` AS t0_r14, `users`.`updated_at` AS t0_r15, `users`.`account_id` AS t0_r16, `users`.`deactivated_at` AS t0_r17, `users`.`role` AS t0_r18, `users`.`super_admin` AS t0_r19, `accounts`.`id` AS t1_r0, `accounts`.`created_at` AS t1_r1, `accounts`.`updated_at` AS t1_r2, `accounts`.`deactivated_at` AS t1_r3, `accounts`.`time_zone` AS t1_r4, `accounts`.`api_key` AS t1_r5, `accounts`.`enterprise` AS t1_r6, `accounts`.`require_branding` AS t1_r7, `accounts`.`manager_id` AS t1_r8, `accounts`.`blocked_ips` AS t1_r9, `accounts`.`blocked_emails` AS t1_r10, `accounts`.`qa_ips` AS t1_r11, `accounts`.`qa_emails` AS t1_r12 FROM `users` LEFT OUTER JOIN `accounts` ON `accounts`.`id` = `users`.`account_id`  ORDER BY `users`.`id` ASC LIMIT 1
NoMethodError: undefined method `shifted_id' for #<User:0x007faa85ce6e68>
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/activemodel-4.2.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
	from (irb):23
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

 It may be your issue.

**Comment by codenamev** [comment]
I am using an `includes` call, but it actually is building the query correctly (I believe you need to wrap your special select statement in parenthesis to get it to build the way you'd expect).

**Comment by bogdan** [comment]
This is not about query builder but query result parser.
Using `()` doesn't fix this issue:

```
 > User.eager_load(:account).select("users.*", "(users.id+100) as shifted_id").first.shifted_id
NoMethodError: undefined method `shifted_id' for #<User:0x007faa85d15880>
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/activemodel-4.2.3/lib/active_model/attribute_methods.rb:433:in `method_missing'
	from (irb):24
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/bogdan/.rvm/gems/ruby-2.2.2@talkable/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'
```

I am asking you 3rd time to provide full query.

Try to change `includes` to `preload`. It may just fix the issue.

**Comment by codenamev** [comment]
I see, it appears this is an unfortunate limitation of active record.

Preloading creates another query, as well as making it impossible to add restrictions on the joins made by the `includes`.

Sorry about not providing the query, but I didn't want to expose any of my client's database structure for security reasons.

Closing this for now.  If I find a solution I will come back and re-open this ticket.

**Comment by bogdan** [comment]
You should probably use a combination of `joins` with `preload`:

``` ruby
User.preload(:account).
  joins(:account).where(accounts: {id: 25}).
  select("users.*", "users.id+100 as shifted_id").first.shifted_id
