### ISSUE TITLE
undefined method `columns'  when I make grid from sql view

### ISSUE THREAD

**Issue by flexloop** [bogdan/datagrid#186]
Hi All-

I am using 
tiny_tds 1.0.4
activerecord-sqlserver-adapter 4.1.2
rails 4.1.2
datagrid 1.4.4
on SQL Server 2008 R2, everything on Windows 7

Datagrid gem works great with SQL tables and simple views, but as soon as I try to use views with joins, even if I don't include columns from the joined tables, I get this error:

```
Showing c:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/datagrid-1.4.4/app/views/datagrid/_table.html.erb where line #13 raised:

undefined method `columns' for #<Arel::Table:0x5bb4758>

_table.html.erb looks like this:

12         <% if assets.any? %>
13           <%= datagrid_rows(grid, assets, options) %>
14         <% else %>
15           <tr><td class="noresults" colspan="100%"><%= I18n.t('datagrid.no_results').html_safe %> 16 </td></tr>
```

Trace below.
Any ideas? 

Thanks-

Michael

```
activerecord-sqlserver-adapter (4.1.2) lib/arel/visitors/sqlserver.rb:433:in `rowtable_orders'
activerecord-sqlserver-adapter (4.1.2) lib/arel/visitors/sqlserver.rb:161:in `visit_Arel_Nodes_SelectStatementWithOffset'
activerecord-sqlserver-adapter (4.1.2) lib/arel/visitors/sqlserver.rb:13:in `visit_Arel_Nodes_SelectStatement'
arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:343:in `visit_Arel_Nodes_Grouping'
arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:399:in `visit_Arel_Nodes_TableAlias'
arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
arel (5.0.1.20140414130214) lib/arel/visitors/to_sql.rb:439:in `visit_Arel_Nodes_JoinSource'
arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
activerecord-sqlserver-adapter (4.1.2) lib/arel/visitors/sqlserver.rb:212:in `source_with_lock_for_select_statement'
activerecord-sqlserver-adapter (4.1.2) lib/arel/visitors/sqlserver.rb:150:in `visit_Arel_Nodes_SelectStatementWithOutOffset'
activerecord-sqlserver-adapter (4.1.2) lib/arel/visitors/sqlserver.rb:15:in `visit_Arel_Nodes_SelectStatement'
arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:22:in `visit'
arel (5.0.1.20140414130214) lib/arel/visitors/visitor.rb:5:in `accept'
activerecord (4.1.2) lib/active_record/connection_adapters/abstract/database_statements.rb:13:in `to_sql'
activerecord (4.1.2) lib/active_record/connection_adapters/abstract/query_cache.rb:67:in `select_all'
activerecord (4.1.2) lib/active_record/relation/calculations.rb:262:in `execute_simple_calculation'
activerecord (4.1.2) lib/active_record/relation/calculations.rb:224:in `perform_calculation'
activerecord (4.1.2) lib/active_record/relation/calculations.rb:119:in `calculate'
activerecord (4.1.2) lib/active_record/relation/calculations.rb:34:in `count'
activerecord (4.1.2) lib/active_record/relation.rb:251:in `empty?'
activerecord (4.1.2) lib/active_record/relation.rb:261:in `any?'
datagrid (1.4.4) app/views/datagrid/_table.html.erb:13:in `block in _c___ails_nstaller__uby______lib_ruby_gems_______gems_datagrid_______app_views_datagrid__table_html_erb__659243260_49523112'
actionview (4.1.2) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
actionview (4.1.2) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
actionview (4.1.2) lib/action_view/helpers/capture_helper.rb:38:in `capture'
actionview (4.1.2) lib/action_view/helpers/tag_helper.rb:97:in `content_tag'
datagrid (1.4.4) app/views/datagrid/_table.html.erb:8:in `_c___ails_nstaller__uby______lib_ruby_gems_______gems_datagrid_______app_views_datagrid__table_html_erb__659243260_49523112'
actionview (4.1.2) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.2) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.2) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.2) lib/action_view/template.rb:143:in `render'
actionview (4.1.2) lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
actionview (4.1.2) lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
actionview (4.1.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.1.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.2) lib/active_support/notifications.rb:159:in `instrument'
actionview (4.1.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionview (4.1.2) lib/action_view/renderer/partial_renderer.rb:278:in `render'
actionview (4.1.2) lib/action_view/renderer/renderer.rb:47:in `render_partial'
actionview (4.1.2) lib/action_view/renderer/renderer.rb:21:in `render'
actionview (4.1.2) lib/action_view/helpers/rendering_helper.rb:32:in `render'
datagrid (1.4.4) lib/datagrid/renderer.rb:84:in `_render_partial'
datagrid (1.4.4) lib/datagrid/renderer.rb:43:in `table'
datagrid (1.4.4) lib/datagrid/helper.rb:42:in `datagrid_table'
app/views/vtests/index.html.erb:4:in `_app_views_vtests_index_html_erb__144282720_34781100'
actionview (4.1.2) lib/action_view/template.rb:145:in `block in render'
activesupport (4.1.2) lib/active_support/notifications.rb:161:in `instrument'
actionview (4.1.2) lib/action_view/template.rb:339:in `instrument'
actionview (4.1.2) lib/action_view/template.rb:143:in `render'
actionview (4.1.2) lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
actionview (4.1.2) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (4.1.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.2) lib/active_support/notifications.rb:159:in `instrument'
actionview (4.1.2) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionview (4.1.2) lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
actionview (4.1.2) lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
actionview (4.1.2) lib/action_view/renderer/template_renderer.rb:53:in `render_template'
actionview (4.1.2) lib/action_view/renderer/template_renderer.rb:17:in `render'
actionview (4.1.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.1.2) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.1.2) lib/action_view/rendering.rb:99:in `_render_template'
actionpack (4.1.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.1.2) lib/action_view/rendering.rb:82:in `render_to_body'
actionpack (4.1.2) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.1.2) lib/action_controller/metal/renderers.rb:32:in `render_to_body'
actionpack (4.1.2) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.1.2) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.1.2) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
activesupport (4.1.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.1.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.1.2) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
actionpack (4.1.2) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
activerecord (4.1.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.1.2) lib/action_controller/metal/instrumentation.rb:40:in `render'
actionpack (4.1.2) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.1.2) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.1.2) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.1.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.1.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.1.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.2) lib/active_support/callbacks.rb:113:in `call'
activesupport (4.1.2) lib/active_support/callbacks.rb:229:in `block in halting'
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `call'
activesupport (4.1.2) lib/active_support/callbacks.rb:166:in `block in halting'
activesupport (4.1.2) lib/active_support/callbacks.rb:86:in `call'
activesupport (4.1.2) lib/active_support/callbacks.rb:86:in `run_callbacks'
actionpack (4.1.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.1.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.1.2) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
activesupport (4.1.2) lib/active_support/notifications.rb:159:in `block in instrument'
activesupport (4.1.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.1.2) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.1.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.1.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.1.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.1.2) lib/abstract_controller/base.rb:136:in `process'
actionview (4.1.2) lib/action_view/rendering.rb:30:in `process'
actionpack (4.1.2) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.1.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.1.2) lib/action_controller/metal.rb:232:in `block in action'
actionpack (4.1.2) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.1.2) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.1.2) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.1.2) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.1.2) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.1.2) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.1.2) lib/action_dispatch/routing/route_set.rb:678:in `call'
rack (1.5.5) lib/rack/etag.rb:23:in `call'
rack (1.5.5) lib/rack/conditionalget.rb:25:in `call'
rack (1.5.5) lib/rack/head.rb:11:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/flash.rb:254:in `call'
rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.1.2) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.1.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
activerecord (4.1.2) lib/active_record/migration.rb:380:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.1.2) lib/active_support/callbacks.rb:82:in `run_callbacks'
actionpack (4.1.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.1.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.1.2) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.1.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.1.2) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.1.2) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.1.2) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.5) lib/rack/runtime.rb:17:in `call'
activesupport (4.1.2) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
actionpack (4.1.2) lib/action_dispatch/middleware/static.rb:64:in `call'
rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
railties (4.1.2) lib/rails/engine.rb:514:in `call'
railties (4.1.2) lib/rails/application.rb:144:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
rack (1.5.5) lib/rack/content_length.rb:14:in `call'
rack (1.5.5) lib/rack/handler/webrick.rb:60:in `service'
c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
c:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

```

**Comment by flexloop** [comment]
Problem seems to go away with
rails 4.2.4 and activerecord-sqlserver-adapter 4.2.15

**Comment by bogdan** [comment]
Show me the grid source code

**Comment by flexloop** [comment]
I made the model to work with the grid that your scaffold created.

class CrudsGrid

  include Datagrid

  scope do
    Crud
  end

  filter(:id, :integer)
  filter(:created_at, :date, :range => true)

  column(:id)
  column(:name)
  column(:created_at) do |model|
    model.created_at.to_date
  end
end


Thank you!

**Comment by bogdan** [comment]
Yes, probably there is some bug in your adapter.... if you fixed it by upgrading.
If not, I would also need a controller and view code. Maybe there is something wrong there.

**Comment by flexloop** [comment]
Thank you for your help. This is a nice gem.
