### ISSUE TITLE
Cannot use Sequel pagination

### ISSUE THREAD

**Issue by sanks64** [bogdan/datagrid#311]
Sequel has [a built-in extension for pagination](https://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/pagination_rb.html) that doesn't seem to work with Datagrid.

```ruby
# all_sites_grid.rb
class AllSitesGrid < BaseGrid
  scope do
    Site
  end
end

# sites_controller.rb
grid = AllSitesGrid.new do
  Site.dataset.paginate(1, 25)
end
```

```
SitesControllerTest#test_#all_sites_table_works:
Sequel::Error: You cannot paginate a dataset that already has a limit
    app/controllers/sites_controller.rb:269:in `all_sites_table'
    test/controllers/sites_controller_test.rb:248:in `block in <class:SitesControllerTest>'
    test/test_helper.rb:23:in `block in run'
    test/test_helper.rb:23:in `run'
```

**Comment by sanks64** [comment]
The workaround that I came up with:

```ruby
# all_sites_grid.rb
class AllSitesGrid < BaseGrid
  scope do
    []
  end
end

# sites_controller.rb
grid = AllSitesGrid.new do
  Site.dataset.paginate(1, 25).to_a
end
```

**Comment by sanks64** [comment]
It works in the console:

```
irb(main):001:0> Site.dataset.paginate(1, 25)
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"sites\" LIMIT 25 OFFSET 0">
```

Not sure what you mean by grid imitation, but this is the error with your suggestion:

```
NoMethodError: undefined method `paginate' for Site:Class
```

**Comment by bogdan** [comment]
Try the following:

``` ruby
# all_sites_grid.rb
class AllSitesGrid < BaseGrid
  scope do
    Site.dataset
  end
end

# sites_controller.rb
grid = AllSitesGrid.new do
  scope.paginate(1, 25)
end
```

**Comment by sanks64** [comment]
The same error even on `master`:

```
Sequel::Error: You cannot paginate a dataset that already has a limit
```

**Comment by bogdan** [comment]
Try the following in console:

```
AllSitesGrid.new.scope.paginate(1,25)
AllSitesGrid.new.assets.paginate(1,25)
```

What is the result?

**Comment by sanks64** [comment]
```
irb(main):001:0> AllSitesGrid.new.scope.paginate(1, 25)
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"sites\" LIMIT 25 OFFSET 0">
irb(main):002:0> AllSitesGrid.new.assets.paginate(1, 25)
=> #<Sequel::Postgres::Dataset: "SELECT * FROM \"sites\" LIMIT 25 OFFSET 0">
```

**Comment by bogdan** [comment]
Try the following too:

```
AllSitesGrid.new{|s| s.paginate(1,25)}.assets.to_a
```

Also, let me know, which specific line is showing up in the backtrace with the error.

**Comment by sanks64** [comment]
Sorry, but can't you try it? It should be easy to reproduce.

**Comment by bogdan** [comment]
I did. It is not reproducing. https://github.com/bogdan/datagrid/blob/98161d5ea9d34f3d18b8c90c1e75673a1b641683/spec/datagrid/drivers/sequel_spec.rb#L45

**Comment by bogdan** [comment]
I have no idea how limit appear in your code. You need to provide a full controller action, view, grid and model source code.

**Comment by sanks64** [comment]
See #312.

**Comment by sanks64** [comment]
Thanks!
